# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: end
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
    - gripper_left_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
manipuator_controller:
  type: position_controllers/JointPositionController
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  gains:
    arm_left_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1